# Generated by Django 5.2.6 on 2025-09-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النقطة')),
                ('path', models.CharField(max_length=200, verbose_name='المسار')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10, verbose_name='الطريقة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('requires_auth', models.BooleanField(default=True, verbose_name='يتطلب مصادقة')),
                ('rate_limit', models.PositiveIntegerField(default=100, verbose_name='حد المعدل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نقطة نهاية API',
                'verbose_name_plural': 'نقاط نهاية API',
                'ordering': ['path', 'method'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المفتاح')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='المفتاح')),
                ('secret', models.CharField(max_length=64, verbose_name='السر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='الصلاحيات')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مفتاح API',
                'verbose_name_plural': 'مفاتيح API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200, verbose_name='النقطة النهائية')),
                ('requests_count', models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات')),
                ('window_start', models.DateTimeField(verbose_name='بداية النافذة')),
                ('window_end', models.DateTimeField(verbose_name='نهاية النافذة')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='محظور')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='محظور حتى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'حد معدل API',
                'verbose_name_plural': 'حدود معدل API',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200, verbose_name='النقطة النهائية')),
                ('method', models.CharField(max_length=10, verbose_name='الطريقة')),
                ('status_code', models.PositiveIntegerField(verbose_name='رمز الحالة')),
                ('response_time', models.FloatField(verbose_name='وقت الاستجابة')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(verbose_name='متصفح المستخدم')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الطلب')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الاستجابة')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'طلب API',
                'verbose_name_plural': 'طلبات API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='الإصدار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_deprecated', models.BooleanField(default=False, verbose_name='مهجور')),
                ('deprecation_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الهجر')),
                ('changelog', models.TextField(blank=True, null=True, verbose_name='سجل التغييرات')),
                ('documentation_url', models.URLField(blank=True, null=True, verbose_name='رابط التوثيق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إصدار API',
                'verbose_name_plural': 'إصدارات API',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الـ Webhook')),
                ('url', models.URLField(verbose_name='الرابط')),
                ('events', models.JSONField(default=list, verbose_name='الأحداث')),
                ('secret', models.CharField(max_length=64, verbose_name='السر')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('error', 'خطأ')], default='active', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='عدد الفشل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100, verbose_name='الحدث')),
                ('payload', models.JSONField(verbose_name='البيانات')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('delivered', 'تم التسليم'), ('failed', 'فشل'), ('retrying', 'إعادة المحاولة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='رمز الحالة')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='نص الاستجابة')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='الحد الأقصى للمحاولات')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد المحاولة التالية')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تسليم Webhook',
                'verbose_name_plural': 'تسليمات Webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
