# Generated by Django 5.2.6 on 2025-09-26 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='apiratelimit',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='api.apikey', verbose_name='مفتاح API'),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.apikey', verbose_name='مفتاح API'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='api.apiversion', verbose_name='الإصدار'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.webhook', verbose_name='الـ Webhook'),
        ),
        migrations.AlterUniqueTogether(
            name='apiendpoint',
            unique_together={('path', 'method', 'version')},
        ),
    ]
