# Generated by Django 5.2.6 on 2026-04-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clearance_level',
            field=models.CharField(choices=[('L1', 'Level 1 - Public OSINT (مصادر مفتوحة)'), ('L2', 'Level 2 - Commercial APIs (تجارية)'), ('L3', 'Level 3 - Private & Leaked (خاصة وتسريبات)'), ('L4', 'Level 4 - Agency / Admin (جهات عليا)')], default='L1', max_length=2, verbose_name='مستوى التصريح الأمني'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='المؤسسة / الجهة'),
        ),
    ]
