# Generated by Django 5.2.6 on 2025-09-27 16:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OSINTTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الأداة')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('tool_type', models.CharField(choices=[('email', 'البريد الإلكتروني'), ('username', 'اسم المستخدم'), ('domain', 'النطاق'), ('ip', 'عنوان IP'), ('phone', 'رقم الهاتف'), ('social', 'وسائل التواصل الاجتماعي'), ('google', 'Google'), ('general', 'عام')], max_length=20, verbose_name='نوع الأداة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('maintenance', 'صيانة'), ('deprecated', 'مهمل')], default='active', max_length=20, verbose_name='الحالة')),
                ('icon', models.CharField(default='fas fa-search', max_length=50, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='اللون')),
                ('requires_auth', models.BooleanField(default=False, verbose_name='يتطلب مصادقة')),
                ('api_key_required', models.BooleanField(default=False, verbose_name='يتطلب مفتاح API')),
                ('rate_limit', models.PositiveIntegerField(default=100, verbose_name='حد المعدل')),
                ('timeout', models.PositiveIntegerField(default=30, verbose_name='المهلة الزمنية')),
                ('tool_path', models.CharField(max_length=200, verbose_name='مسار الأداة')),
                ('executable_name', models.CharField(max_length=100, verbose_name='اسم الملف التنفيذي')),
                ('command_template', models.TextField(verbose_name='قالب الأمر')),
                ('config_schema', models.JSONField(blank=True, default=dict, verbose_name='مخطط الإعدادات')),
                ('supported_formats', models.JSONField(blank=True, default=list, verbose_name='الصيغ المدعومة')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستخدامات')),
                ('success_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='معدل النجاح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'أداة OSINT',
                'verbose_name_plural': 'أدوات OSINT',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OSINTSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=500, verbose_name='الهدف')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('running', 'قيد التشغيل'), ('completed', 'مكتملة'), ('failed', 'فشلت'), ('cancelled', 'ملغية')], default='pending', max_length=20, verbose_name='الحالة')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='الإعدادات')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='الخيارات')),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='التقدم')),
                ('current_step', models.CharField(blank=True, max_length=200, verbose_name='الخطوة الحالية')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='عدد النتائج')),
                ('results_summary', models.JSONField(blank=True, default=dict, verbose_name='ملخص النتائج')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإكمال')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='المدة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('log_file', models.FileField(blank=True, null=True, upload_to='osint_logs/', verbose_name='ملف السجل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osint_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='osint_tools.osinttool', verbose_name='الأداة')),
            ],
            options={
                'verbose_name': 'جلسة OSINT',
                'verbose_name_plural': 'جلسات OSINT',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OSINTResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('email', 'بريد إلكتروني'), ('username', 'اسم مستخدم'), ('profile', 'ملف شخصي'), ('domain', 'نطاق'), ('ip', 'عنوان IP'), ('phone', 'رقم هاتف'), ('social_media', 'وسائل التواصل'), ('website', 'موقع ويب'), ('image', 'صورة'), ('document', 'مستند'), ('other', 'أخرى')], max_length=20, verbose_name='نوع النتيجة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('url', models.URLField(blank=True, verbose_name='الرابط')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات الخام')),
                ('confidence', models.CharField(choices=[('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض'), ('unknown', 'غير معروف')], default='unknown', max_length=20, verbose_name='مستوى الثقة')),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='درجة الثقة')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='المصدر')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='العلامات')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='البيانات الوصفية')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاكتشاف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='osint_tools.osintsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'نتيجة OSINT',
                'verbose_name_plural': 'نتائج OSINT',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='OSINTReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(choices=[('summary', 'ملخص'), ('detailed', 'مفصل'), ('executive', 'تنفيذي'), ('technical', 'تقني')], max_length=20, verbose_name='نوع التقرير')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('json', 'JSON'), ('csv', 'CSV'), ('xml', 'XML')], max_length=10, verbose_name='الصيغة')),
                ('content', models.TextField(blank=True, verbose_name='المحتوى')),
                ('summary', models.TextField(blank=True, verbose_name='الملخص')),
                ('recommendations', models.TextField(blank=True, verbose_name='التوصيات')),
                ('file', models.FileField(blank=True, null=True, upload_to='osint_reports/', verbose_name='ملف التقرير')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم الملف')),
                ('include_raw_data', models.BooleanField(default=False, verbose_name='تضمين البيانات الخام')),
                ('include_metadata', models.BooleanField(default=True, verbose_name='تضمين البيانات الوصفية')),
                ('include_charts', models.BooleanField(default=True, verbose_name='تضمين الرسوم البيانية')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('downloaded_count', models.PositiveIntegerField(default=0, verbose_name='عدد التحميلات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osint_reports', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='osint_tools.osintsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'تقرير OSINT',
                'verbose_name_plural': 'تقارير OSINT',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='OSINTActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('tool_run', 'تشغيل أداة'), ('report_generated', 'إنشاء تقرير'), ('config_updated', 'تحديث إعداد'), ('session_started', 'بدء جلسة'), ('session_completed', 'إكمال جلسة'), ('result_exported', 'تصدير نتيجة'), ('error_occurred', 'حدث خطأ')], max_length=30, verbose_name='الإجراء')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osint_activities', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='osint_tools.osintsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'سجل نشاط OSINT',
                'verbose_name_plural': 'سجلات أنشطة OSINT',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OSINTConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100, verbose_name='اسم الإعداد')),
                ('config_data', models.JSONField(default=dict, verbose_name='بيانات الإعداد')),
                ('api_keys', models.JSONField(blank=True, default=dict, verbose_name='مفاتيح API')),
                ('proxy_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات البروكسي')),
                ('timeout', models.PositiveIntegerField(default=30, verbose_name='المهلة الزمنية')),
                ('retry_count', models.PositiveIntegerField(default=3, verbose_name='عدد المحاولات')),
                ('concurrent_requests', models.PositiveIntegerField(default=5, verbose_name='الطلبات المتزامنة')),
                ('anonymize_results', models.BooleanField(default=False, verbose_name='إخفاء هوية النتائج')),
                ('store_results', models.BooleanField(default=True, verbose_name='حفظ النتائج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osint_configs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='osint_tools.osinttool', verbose_name='الأداة')),
            ],
            options={
                'verbose_name': 'إعداد OSINT',
                'verbose_name_plural': 'إعدادات OSINT',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'tool', 'config_name')},
            },
        ),
    ]
