# Generated by Django 5.2.6 on 2026-04-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintreport',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف مهمة Celery'),
        ),
        migrations.AddField(
            model_name='osintreport',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='رسالة الخطأ'),
        ),
        migrations.AddField(
            model_name='osintreport',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('running', 'قيد الإنشاء'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='osintsession',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف مهمة Celery'),
        ),
    ]
