# Generated by Django 5.2.6 on 2026-04-12 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint_tools', '0002_osintreport_celery_task_id_osintreport_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='osinttool',
            name='required_clearance',
            field=models.CharField(choices=[('L1', 'Level 1 - Public OSINT'), ('L2', 'Level 2 - Commercial APIs'), ('L3', 'Level 3 - Private & Leaked'), ('L4', 'Level 4 - Admins Only')], default='L1', max_length=2, verbose_name='الصلاحية المطلوبة'),
        ),
        migrations.AddField(
            model_name='osinttool',
            name='source_type',
            field=models.CharField(choices=[('open', 'OSINT (مصادر مفتوحة)'), ('private', 'Private API (واجهات خاصة/مدفوعة)'), ('leaked', 'Leaked Data (تسريبات Dark Web)')], default='open', max_length=20, verbose_name='نوع المصدر'),
        ),
        migrations.CreateModel(
            name='InvestigationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان القضية / الهدف')),
                ('description', models.TextField(blank=True, verbose_name='وصف القضية')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'قيد التحقيق'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='الحالة')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='العلامات (Tags)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفتح')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_cases', to=settings.AUTH_USER_MODEL, verbose_name='المحقق')),
            ],
            options={
                'verbose_name': 'قضية استخباراتية',
                'verbose_name_plural': 'القضايا الاستخباراتية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='osintsession',
            name='investigation_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='osint_tools.investigationcase', verbose_name='تتبع للقضية المفتوحة'),
        ),
    ]
