# Generated by Django 5.2.6 on 2026-04-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint_tools', '0003_osinttool_required_clearance_osinttool_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
