# Generated by Django 5.2.6 on 2026-04-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint_tools', '0004_add_updated_at_to_osintreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osintsession',
            name='current_step',
            field=models.TextField(blank=True, verbose_name='الخطوة الحالية'),
        ),
    ]
