# Generated by Django 5.2.6 on 2026-04-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osint_tools', '0005_alter_osintsession_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationcase',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المحقق'),
        ),
    ]
